### ISSUE TITLE
References to node["root_path"] raise KeyError on dbt >= 1.4.0 

### ISSUE THREAD

**Issue by rwhitten577** [Montreal-Analytics/dbt-gloss#101]
**Describe the bug**
dbt 1.4 removed `root_path` from manifest.json as described [in the docs](https://docs.getdbt.com/reference/artifacts/manifest-json#:~:text=defines%20this%20resource.-,root_path,-%3A%20Absolute%20file%20path)

References to it in pre-commit checks fail when the expected key is not available. Example traceback:

```
Traceback (most recent call last):
  File "/Users/<username>/.cache/pre-commit/repogjttv6__/py_env-python3.8/bin/check-model-has-properties-file", line 8, in <module>
    sys.exit(main())
  File "/Users/<username>/.cache/pre-commit/repogjttv6__/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/check_model_has_properties_file.py", line 56, in main
    status_code, _ = has_properties_file(paths=args.filenames, manifest=manifest)
  File "/Users/<username>/.cache/pre-commit/repogjttv6__/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/check_model_has_properties_file.py", line 22, in has_properties_file
    paths = get_missing_file_paths(paths, manifest)
  File "/Users/<username>/.cache/pre-commit/repogjttv6__/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/utils.py", line 491, in get_missing_file_paths
    add_related_ymls(path, nodes, paths_with_missing, include_ephemeral)
  File "/Users/<username>/.cache/pre-commit/repogjttv6__/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/utils.py", line 467, in add_related_ymls
    root_folder = Path(node["root_path"]).name
KeyError: 'root_path'

```

**To Reproduce**
1. Install dbt >= 1.4.0
2. Add a check like `check-model-has-properties-file` to `.pre-commit-config.yaml`
3. Run pre-commit

**Expected behavior**
Files are able to be resolved without the KeyError and without the presence of `root_path` in nodes. 

**Version:**
v0.1.0

**Additional context**

**Comment by mbhoopathy** [comment]
The issue exists for other hooks as well i.e. 
`check-model-columns-have-desc`
`check-model-has-description`

dbt version: 1.5.1

**Comment by BAntonellini** [comment]
Hi everyone, thanks for your contributions. Some time ago we released `v1.1.0` with some tweaks, enhancements and bug fixes to the original pre-commit-dbt

Are you using this latest `ref`? References to `node["root_path"]` no longer exist.

**Comment by mbhoopathy** [comment]
Yes @BAntonellini  upgrading to v1.1.0 resolves this error. Thank you.

**Comment by mbhoopathy** [comment]
Closing the issue, as the error doesn't show up when upgrading to version v.1.1.0 or further.
