### ISSUE TITLE
check-source-columns-have-desc doesn't support sql models with jinja at the top

### ISSUE THREAD

**Issue by fathom-parth** [Montreal-Analytics/dbt-gloss#126]
**Describe the bug**
When running check-source-columns-have-desc over a model that starts with some jinja, I get the following error:

```
Check for source column descriptions..........................................Failed
hookid: check-source-columns-have-desc

Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/bin/check-source-columns-have-desc", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 52, in main
    hook_properties = check_column_desc(paths=args.filenames)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 23, in check_column_desc
    for schema in schemas:
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/utils.py", line 250, in get_source_schemas
    schema = safe_load(yml_file.open())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 540, in parse_flow_mapping_first_key
    return self.parse_flow_mapping_key(first=True)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 543, in parse_flow_mapping_key
    if not self.check_token(FlowMappingEndToken):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "macros/checks.sql", line 4, column 2
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/bin/check-source-columns-have-desc", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 52, in main
    hook_properties = check_column_desc(paths=args.filenames)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 23, in check_column_desc
    for schema in schemas:
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/utils.py", line 250, in get_source_schemas
    schema = safe_load(yml_file.open())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 550, in parse_flow_mapping_key
    "expected ',' or '}', but got %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a flow mapping
  in "models/intermediate/training/int_coin__gold_dx_per_page_joined_with_text.sql", line 1, column 1
expected ',' or '}', but got '{'
  in "models/intermediate/training/int_coin__gold_dx_per_page_joined_with_text.sql", line 6, column 10
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/bin/check-source-columns-have-desc", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 52, in main
    hook_properties = check_column_desc(paths=args.filenames)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 23, in check_column_desc
    for schema in schemas:
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/utils.py", line 251, in get_source_schemas
    for source in schema.get("sources", []):
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/bin/check-source-columns-have-desc", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 52, in main
    hook_properties = check_column_desc(paths=args.filenames)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/check_source_columns_have_desc.py", line 23, in check_column_desc
    for schema in schemas:
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/dbt_checkpoint/utils.py", line 250, in get_source_schemas
    schema = safe_load(yml_file.open())
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 540, in parse_flow_mapping_first_key
    return self.parse_flow_mapping_key(first=True)
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/parser.py", line 543, in parse_flow_mapping_key
    if not self.check_token(FlowMappingEndToken):
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/root/.cache/pre-commit/repoie43ai7m/py_env-python3.7/lib/python3.7/site-packages/yaml/scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "models/intermediate/training/int_night__gold_per_charge_text_aggregated_to_per_encounter_text.sql", line 4, column 2
```

Note: It's weird that it's running a yaml parser over sql?

**To Reproduce**
1. Define a model like so:
```sql
{# TKTKTKTK #}


{% set static_cols = ["patient_id"] %}


select 1
```
(Didn't actually test this but it probably reproduces...)
2. Add a yaml file in the same folder as the above model.
3. Run the `check-source-columns-have-desc` hook over your models and yml files.
4. Observe above error.

**Expected behavior**
I expected it not to error from having jinja inside a model. Additionally, it's weird that it's running over this model at all given that it's not a source?

**Version:**
v1.1.0

**Additional context**
n/a

**Comment by SeppBerkner** [comment]
It seems I have a similar error with the `check-source-childs` hook. I have the following dbt model:

```
{{ config(schema='stg_geo_bb') }}

SELECT 
    -- Identifikation
    oid AS kreis_id,
    ags::text AS kreis_schluessel,
    ...
```

When I stage the file and test another source test like `pre-commit run check-source-has-loader` I get the response

`Check the source has loader option...................(no files to check)Skipped`

However, when I do the same with `pre-commit run check-source-childs` I get this response:

```
Check the source has max/min number of childs............................Failed
- hook id: check-source-childs
- exit code: 1

Traceback (most recent call last):
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/bin/check-source-childs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/check_source_childs.py", line 95, in main
    hook_properties = check_child_parent_cnt(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/check_source_childs.py", line 29, in check_child_parent_cnt
    for schema in schemas:
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/utils.py", line 347, in get_source_schemas
    schema = checkpoint_safe_load(yml_file.open())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/utils.py", line 126, in checkpoint_safe_load
    return safe_load(stream) or {}
           ^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/Users/jbe/.cache/pre-commit/repowl1gage1/py_env-python3.11/lib/python3.11/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "transform/models/b_staging/geo_aemter/geo_bb/stg_geo_bb__alkis__kreis.sql", line 3, column 1
```

My `.pre-commit-config.yaml` looks like this:

```
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v2.0.3
  hooks:
    # Datenbank
    - id: check-column-name-contract
      args: [--pattern, "(ist|hat)_.*", --dtypes, boolean, "--"]

    # DBT general
    - id: dbt-docs-generate
    - id: dbt-parse

    # Models
    - id: check-model-has-description
    - id: check-model-columns-have-desc
    - id: check-model-has-all-columns
    - id: check-model-has-contract
    - id: check-model-has-tests
      args: ["--test-cnt", "2", "--"]
    - id: check-model-has-meta-keys
      args: ['--meta-keys', 'dagster', "--"]
    - id: check-model-name-contract
      args: [--pattern, "stg_.*"]
      files: models/b_staging/
    - id: check-model-name-contract
      args: [--pattern, "int_.*"]
      files: models/c_intermediate/
    - id: check-model-name-contract
      args: [--pattern, "snap_.*"]
      files: snapshots/
    - id: check-model-parents-and-childs
      args: ["--min-parent-cnt", "1", "--"]
    - id: check-script-has-no-table-name

    # Sources
    - id: check-source-table-has-description
    - id: check-source-has-all-columns
    - id: check-source-columns-have-desc
    - id: check-source-has-meta-keys
      args: ['--meta-keys', 
        'Data Owner (Technisch)', 
        'Data Owner (Inhaltlich)',
        'Datenstand',
        'Updatezyklus',
        'Abrufzyklus',
        'Datenformat',
        'Nutzung',
        'Datenquelle',
        'Externe Dokumentation',
        'Identifikator',
        'Support-Kontakt',
        "--"]
    - id: check-source-has-freshness
      args: ["--freshness", "error_after", "warn_after", "--"]
    - id: check-source-has-loader
    - id: check-source-childs
      args: ["--min-child-cnt", "1", "--"]

    # Macro
    - id: check-macro-has-description
    - id: check-macro-arguments-have-desc

```

EDIT:

Also, as mentioned by @fathom-parth the hook `check-source-columns-have-desc` checks the dbt model anyways and doesn't skip it, even though it is not a yaml file, but it doesn't return an error in my case:
`Check for source column descriptions.....................................Passed`

EDIT 2:

OK, the point I made in my previous EDIT is basically due to the issue #163 , which I could resolve. However, my main point stil stands.
