### ISSUE TITLE
[Help] dbt-test & dbt-docs-generate are failing when commiting via Vscode but pass during manual pre-commit run

### ISSUE THREAD

**Issue by adrian-bogle** [Montreal-Analytics/dbt-gloss#159]
Passing the `--manifest` argument allows all the check hooks to pass with flying colors. I'd love to use the `dbt-project-dir` but no combination of pointing to the `manifest.json` file seems to work.

full manifest argument
`args: ["--manifest","src/waterworks/dbt/target/manifest.json"]`

I'd love an example of how to properly path the dbt root directly since it's not at the root level. I can't seem to find a single example

**Comment by noel** [comment]
Did you try adding it to the .dbt-checkpoint file?

**Comment by adrian-bogle** [comment]
Yes, trying to figure how what path it needs? My root is in
src/waterworks/dbt

**Comment by noel** [comment]
like this
https://github.com/datacoves/balboa/blob/main/.dbt-checkpoint.yaml#L3

change `transform` to `src/waterworks/dbt`

**Comment by adrian-bogle** [comment]
Thanks, I'll check it out!

**Comment by adrian-bogle** [comment]
Here is my `.dbt-checkpoint.yaml` file:
```
version: 1
disable-tracking: true
dbt-project-dir: src/waterworks/dbt
```

Here's the error I am getting, I wonder if I need `.dbt-checkpoint.yaml` in a dbt run?
```
17:40:04  Running with dbt=1.6.6
17:40:04  Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path **C:\Users\**\Documents\GitHub\**\dbt_project.yml**
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
```

Correct Path = **C:\Users\**\Documents\GitHub\**\src\waterworks\dbt\dbt_project.yml**

**Comment by adrian-bogle** [comment]
Well, I can get it to work and pass when I manually run `pre-commit run`. But when I actually submit a commit via VSCode I get the following errors for `dbt-test` & `dbt docs generate`

All check hooks pass with flying colors:
```
Check the script does not contain a semicolon............................Passed
Check the script has not table name......................................Passed
Check the script has existing refs and sources...........................Passed
Check the model has description..........................................Passed
Check the model has properties file......................................Passed
```

```
Traceback (most recent call last):
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\Scripts\dbt-docs-generate.EXE\__main__.py", line 7, in <module>
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\lib\site-packages\dbt_checkpoint\dbt_docs_generate.py", line 37, in main
    return run_dbt_cmd(cmd)
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\lib\site-packages\dbt_checkpoint\utils.py", line 341, in run_dbt_cmd
    output = cmd_output(*list(filter(None, cmd)), expected_code=0)
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\lib\site-packages\dbt_checkpoint\utils.py", line 103, in cmd_output
    proc = subprocess.Popen(cmd, **kwargs)
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Executing cmd: `dbt docs generate --no-compile --project-dir src/waterworks/dbt`
```

```
Traceback (most recent call last):
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\Scripts\dbt-test.EXE\__main__.py", line 7, in <module>
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\lib\site-packages\dbt_checkpoint\dbt_test.py", line 57, in main
    return run_dbt_cmd(cmd)
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\lib\site-packages\dbt_checkpoint\utils.py", line 341, in run_dbt_cmd
    output = cmd_output(*list(filter(None, cmd)), expected_code=0)
  File "C:\Users\AdrianBogle\.cache\pre-commit\repobc10wcfr\py_env-python3.8\lib\site-packages\dbt_checkpoint\utils.py", line 103, in cmd_output
    proc = subprocess.Popen(cmd, **kwargs)
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AdrianBogle\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Executing cmd: `dbt test -m account_dimensions_monthly+ --project-dir src/waterworks/dbt`
```
