### ISSUE TITLE
`check-model-has-description` raises `IsADirectoryError` intermittently

### ISSUE THREAD

**Issue by shippy** [Montreal-Analytics/dbt-gloss#221]
**Describe the bug**
When running the pre-commit hook `check-model-has-description` with non-standard directory and target locations (`greybox_conversion/transform` and `greybox_conversion/.meltano`) errors out with a `IsADirectoryError` because it somehow picks up the target location for a source of YAML files, and then it's surprised when the target directory YAML file actually is a directory that contains the SQL for the tests defined in the project directory YAML file.

**To Reproduce**
1. Set up a dbt project in `meltano_pipeline/transform`
2. Set up a dbt target directory in `meltano_pipeline/.meltano` via `DBT_TARGET_PATH`
3. Set up pre-commit hook with the following definition:
     ```yaml
     - id: check-model-has-properties-file
       files: ^meltano_pipeline/transform/models/
       args: [ --manifest, meltano_pipeline/.meltano/manifest.json ]
     ```
4. Set up a `models/base/model.sql` with `models/base/model.yml` file that contains at least one model test
5. Stage and run `pre-commit`

**Expected behavior**
This hook should only check against YAML files in the project directory.

**Version:**
v2.0.1

**Additional context**
Here's what the traceback looks like - most other hooks don't have this problem:

```
Check the model has properties file......................................Passed
Check the model has description..........................................Failed
- hook id: check-model-has-description
- exit code: 1

Traceback (most recent call last):
  File "/Users/simon/.cache/pre-commit/repojqwpib0c/py_env-python3.11/bin/check-model-has-description", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/simon/.cache/pre-commit/repojqwpib0c/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/check_model_has_description.py", line 69, in main
    hook_properties = has_description(
                      ^^^^^^^^^^^^^^^^
  File "/Users/simon/.cache/pre-commit/repojqwpib0c/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/check_model_has_description.py", line 42, in has_description
    in_schemas = {
                 ^
  File "/Users/simon/.cache/pre-commit/repojqwpib0c/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/check_model_has_description.py", line 42, in <setcomp>
    in_schemas = {
                 ^
  File "/Users/simon/.cache/pre-commit/repojqwpib0c/py_env-python3.11/lib/python3.11/site-packages/dbt_checkpoint/utils.py", line 307, in get_model_schemas
    with open(yml_file, "r") as file:
         ^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'greybox_conversion/.meltano/run/greybox_transformation/models/achievements/achievements.yml'

Check the model columns have description.............(no files to check)Skipped
Check the model has all columns in properties file...(no files to check)Skipped
Check that model has tests...............................................Passed
```

I tested whether including an `exclude: ^meltano_pipeline/.meltano/.*` would do anything, since my reading of [the related hook](https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/dbt_checkpoint/check_model_has_description.py) suggested it might, but either I'm using an incorrect format or it doesn't work.

**Comment by k0x2e** [comment]
This `IsADirectoryError` happens because the recursive glob in `get_missing_file_paths` walks the entire filesystem from CWD including `.meltano/`, `target/`, `.venv/`, etc., and then tries to read directories as YAML files. The same root cause is tracked in #348 and #349. Consolidating there and closing this one.
