### ISSUE TITLE
check-source-childs compilation error

### ISSUE THREAD

**Issue by paramjitsingh006** [Montreal-Analytics/dbt-gloss#246]
**Describe the bug**
Compilation error trying to run the hook check-source-childs as below.

```
Traceback (most recent call last):
  File "/Users/xxx/.cache/pre-commit/repo_wlk5uae/py_env-python3/bin/check-source-childs", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/.cache/pre-commit/repo_wlk5uae/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/check_source_childs.py", line 95, in main
    hook_properties = check_child_parent_cnt(
  File "/Users/xxx/.cache/pre-commit/repo_wlk5uae/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/check_source_childs.py", line 29, in check_child_parent_cnt
    for schema in schemas:
  File "/Users/xxx/.cache/pre-commit/repo_wlk5uae/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/utils.py", line 347, in get_source_schemas
    schema = checkpoint_safe_load(yml_file.open())
  File "/Users/xxx/.cache/pre-commit/repo_wlk5uae/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/utils.py", line 126, in checkpoint_safe_load
    return safe_load(stream) or {}
  File "/Users/xxx/.cache/pre-commit/repo_wlk5uae/py_env-python3/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
```

**To Reproduce**
1. using dbt-core version 1.7.18, run `dbt parse`
2. Add hook in pre-commit as below
```
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.3
      - id: check-source-childs
        name: Check unused sources
        args: ["--min-child-cnt", "1", "--"]
```
4. `pre-commit run`

In the manifest file, the `sources` comes up as list of lists instead of list of dicts (which I think the code is expecting)
`expected ',' or '}', but got '['`

excerpt from manifest.json
```
"sources":[
            [
               "authcleansed",
               "authenticated_user"
            ],
            [
               "authcleansed",
               "two_factor_profile"
            ]
         ]
```

**Expected behavior**
Compile successfully.

**Version:**
v2.0.3

**Additional context**

**Comment by rkudulis** [comment]
fix

```
- id: check-source-childs
    args: ["--min-child-cnt", "1", "--"]
    files: ^models/.*\.yml$
```

**Comment by k0x2e** [comment]
Closing as not a bug. The args list for dbt-checkpoint hooks must end with `"--"` to separate hook arguments from filenames passed by pre-commit. Adding `args: ["--min-child-cnt", "1", "--"]` resolves the error. This is documented in HOOKS.md.
